handlebars:
  suffix: .html

server:
  tomcat:
    accept-count: 2 # 대기열에 수용할 수 있는 최대 연결 요청 수
    max-connections: 2 # 서버가 동시에 처리할 수 있는 최대 연결 수
    threads:
      min-spare: 2
      max: 2 # 동시 실행 가능한 스레드 수
  compression:
    enabled: true
    min-response-size: 10
